### ISSUE TITLE
availability zones hard coded few places

### ISSUE THREAD

**Issue by NudeSurfer** [HugooB/AWS-EC2-spotpricehistory#3]
availability zones hard coded to few places:
vpcs = ["us-east-2a", "us-east-2b", "us-east-2c"]

could be better if used:
    vpcs = df.VPC.unique()

**Comment by HugooB** [comment]
Hey man, thanks for looking into my code! I will work on your proposed changes when I've got time for it, but feel free to create a fork and work on it yourself!
